-- Bloqueia o acesso às tabelas pela API pública do Supabase (PostgREST).
-- O app conecta como dono das tabelas e não é afetado. Em Postgres comum não muda nada.
ALTER TABLE "users" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "characters" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "funnels" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "funnel_nodes" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "funnel_edges" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "leads" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "conversations" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "messages" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "products" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "offers" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "payments" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "webhook_logs" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "tags" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "lead_tags" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "events" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "automations" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "experiments" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "experiment_variants" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "_prisma_migrations" ENABLE ROW LEVEL SECURITY;
